# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apple.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='apple.proto',
  package='apple',
  syntax='proto3',
  serialized_options=b'\n\025com.zeaho.proto.appleB\nAppleProtoP\001\242\002\003HLW',
  serialized_pb=b'\n\x0b\x61pple.proto\x12\x05\x61pple\"\x1c\n\x0c\x41ppleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nAppleReply\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x06\x46\x61rmer\x12\x34\n\x08GetApple\x12\x13.apple.AppleRequest\x1a\x11.apple.AppleReply\"\x00\x42+\n\x15\x63om.zeaho.proto.appleB\nAppleProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_APPLEREQUEST = _descriptor.Descriptor(
  name='AppleRequest',
  full_name='apple.AppleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apple.AppleRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=50,
)


_APPLEREPLY = _descriptor.Descriptor(
  name='AppleReply',
  full_name='apple.AppleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='apple.AppleReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['AppleRequest'] = _APPLEREQUEST
DESCRIPTOR.message_types_by_name['AppleReply'] = _APPLEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppleRequest = _reflection.GeneratedProtocolMessageType('AppleRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPLEREQUEST,
  '__module__' : 'apple_pb2'
  # @@protoc_insertion_point(class_scope:apple.AppleRequest)
  })
_sym_db.RegisterMessage(AppleRequest)

AppleReply = _reflection.GeneratedProtocolMessageType('AppleReply', (_message.Message,), {
  'DESCRIPTOR' : _APPLEREPLY,
  '__module__' : 'apple_pb2'
  # @@protoc_insertion_point(class_scope:apple.AppleReply)
  })
_sym_db.RegisterMessage(AppleReply)


DESCRIPTOR._options = None

_FARMER = _descriptor.ServiceDescriptor(
  name='Farmer',
  full_name='apple.Farmer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=83,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetApple',
    full_name='apple.Farmer.GetApple',
    index=0,
    containing_service=None,
    input_type=_APPLEREQUEST,
    output_type=_APPLEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FARMER)

DESCRIPTOR.services_by_name['Farmer'] = _FARMER

# @@protoc_insertion_point(module_scope)
