# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: water.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='water.proto',
  package='water',
  syntax='proto3',
  serialized_options=b'\n\025com.zeaho.proto.waterB\nWaterProtoP\001\242\002\003HLW',
  serialized_pb=b'\n\x0bwater.proto\x12\x05water\"\x1d\n\x0cWaterRequest\x12\r\n\x05price\x18\x01 \x01(\x02\"\x1d\n\nWaterReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x82\x01\n\x0cWaterCompany\x12<\n\x0e\x42uyStreamWater\x12\x13.water.WaterRequest\x1a\x11.water.WaterReply\"\x00\x30\x01\x12\x34\n\x08\x42uyWater\x12\x13.water.WaterRequest\x1a\x11.water.WaterReply\"\x00\x42+\n\x15\x63om.zeaho.proto.waterB\nWaterProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_WATERREQUEST = _descriptor.Descriptor(
  name='WaterRequest',
  full_name='water.WaterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='water.WaterRequest.price', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=51,
)


_WATERREPLY = _descriptor.Descriptor(
  name='WaterReply',
  full_name='water.WaterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='water.WaterReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['WaterRequest'] = _WATERREQUEST
DESCRIPTOR.message_types_by_name['WaterReply'] = _WATERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WaterRequest = _reflection.GeneratedProtocolMessageType('WaterRequest', (_message.Message,), {
  'DESCRIPTOR' : _WATERREQUEST,
  '__module__' : 'water_pb2'
  # @@protoc_insertion_point(class_scope:water.WaterRequest)
  })
_sym_db.RegisterMessage(WaterRequest)

WaterReply = _reflection.GeneratedProtocolMessageType('WaterReply', (_message.Message,), {
  'DESCRIPTOR' : _WATERREPLY,
  '__module__' : 'water_pb2'
  # @@protoc_insertion_point(class_scope:water.WaterReply)
  })
_sym_db.RegisterMessage(WaterReply)


DESCRIPTOR._options = None

_WATERCOMPANY = _descriptor.ServiceDescriptor(
  name='WaterCompany',
  full_name='water.WaterCompany',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=85,
  serialized_end=215,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuyStreamWater',
    full_name='water.WaterCompany.BuyStreamWater',
    index=0,
    containing_service=None,
    input_type=_WATERREQUEST,
    output_type=_WATERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BuyWater',
    full_name='water.WaterCompany.BuyWater',
    index=1,
    containing_service=None,
    input_type=_WATERREQUEST,
    output_type=_WATERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WATERCOMPANY)

DESCRIPTOR.services_by_name['WaterCompany'] = _WATERCOMPANY

# @@protoc_insertion_point(module_scope)
